version: '3.5'
services:
  web_dev:
    build: .
    ports:
     - "4000:4000"
    volumes:
     - .:/usr/src/app
    environment:
     - ENV=development
     - PORT=4000
#     - DB=mongodb://mongodb:27017/todoDev
     - DB=mongodb://mongodb:27017/components
     - SECRET='to-do-app-secret'
#  api-gateway:
#    container_name: flasktodo_default
#    image: api-gatewawy
##    ports: 
##      - 9090:8080
#    restart:
#      on-failure
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  default:
    external:
      name: flasktodo_default
