version: '3.5'
services:
  web_prod:
    build: .
    ports:
     - "3000:4000"
    volumes:
     - .:/app
    environment:
     - ENV=production
     - PORT=4000
     - DB=mongodb://localhost:27017/todoProd
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks: 
  default:
    name: web_prod